version: '3'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    volumes:
      - ./zookeeper:/home
  broker:
    image: confluentinc/cp-kafka:7.3.2
    container_name: broker
    depends_on:
      - zookeeper
    links:
      - zookeeper
    ports:
      - "9092:9092"
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:9092,PLAINTEXT_INTERNAL://broker:29092 
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
    volumes:
      - ./broker/:/home
  fact_api:
    image: fact-api
    ports:
      - 8000:80
    build: fastapi/.
  kafkaproducer:
    image: kafkaproducer
    build: kafka_producer/.
    container_name: kafkaproducer
    hostname: kafkaproducer
    links:
      - broker
    depends_on:
      - broker
    user: root
    environment:
      KAFKA_BROKER: broker:9092 
    volumes:
      - ./kafka_producer/:/home
  kafkaconsumer:
    image: kafkaconsumer
    build: kafka_consumer/.
    container_name: kafkaconsumer
    hostname: kafkaconsumer
    user: root
    links:
      - broker
      - kafkaproducer
    depends_on:
      - broker
      - kafkaproducer
    environment:
      KAFKA_BROKER: broker:9092 
    volumes:
      - ./kafka_consumer/:/home
